"""HLTV 订阅插件配置"""

from pydantic import BaseModel
from nonebot import get_plugin_config


class Config(BaseModel):
    """HLTV 订阅插件配置"""

    # HLTV API 配置
    hltv_min_delay: float = 5.0   # 最小延迟（秒）- 用于重试时的延迟基数
    hltv_timeout: int = 15        # 超时时间（秒）
    hltv_timezone: str = "Asia/Shanghai"  # 时区

    # 调度配置
    hltv_auto_unsub_delay_days: int = 2  # 赛事结束后延迟多少天自动取消订阅
    hltv_notified_ttl_days: int = 30  # 推送去重状态保留天数
    hltv_scheduler_max_parallel: int = 3  # 多赛事轮询并发上限（防止请求风暴）
    hltv_scheduler_jitter_seconds: int = 8  # 每赛事 job 触发抖动，避免同刻并发

    # 水印配置
    hltv_watermark_text: str = "Designed by Hakuchumu\nGenerated by HakuBot"  # 自定义水印文本，支持换行

    # 代理配置（可选）
    hltv_proxy_list: list[str] = []  # 代理列表


# 获取配置
plugin_config = get_plugin_config(Config)
