"""HLTV 订阅插件配置"""

from pydantic import BaseModel, Field
from nonebot import get_plugin_config


class Config(BaseModel):
    """HLTV 订阅插件配置"""

    # FlareSolverr 会话独立于 Bot 进程，重启 Bot 时继续复用。
    hltv_flaresolverr_url: str = "http://127.0.0.1:8191/v1"
    hltv_flaresolverr_timeout_seconds: int = Field(default=60, gt=0)
    hltv_request_interval_seconds: float = Field(default=15.0, gt=0)
    hltv_block_cooldown_seconds: int = Field(default=600, gt=0)
    hltv_block_cooldown_max_seconds: int = Field(default=7200, gt=0)
    hltv_timezone: str = "Asia/Shanghai"  # 时区

    # 调度配置
    hltv_auto_unsub_delay_days: int = 2  # 赛事结束后延迟多少天自动取消订阅
    hltv_notified_ttl_days: int = 30  # 推送去重状态保留天数
    hltv_scheduler_jitter_seconds: int = 8  # 每赛事 job 触发抖动，避免同刻并发

    # 水印配置
    hltv_watermark_text: str = (
        "Designed by Hakuchumu\nGenerated by HakuBot"  # 自定义水印文本，支持换行
    )


# 获取配置
plugin_config = get_plugin_config(Config)
