"""HLTV 订阅插件配置"""

from pydantic import BaseModel
from nonebot import get_plugin_config


class Config(BaseModel):
    """HLTV 订阅插件配置"""
    
    # HLTV API 配置
    hltv_min_delay: float = 5.0   # 最小延迟（秒）- 用于重试时的延迟基数
    hltv_timeout: int = 15        # 超时时间（秒）
    hltv_timezone: str = "Asia/Shanghai"  # 时区
    
    # 水印配置
    hltv_watermark_text: str = "Designed by Hakuchumu\nGenerated by HakuBot"  # 自定义水印文本，支持换行
    
    # 代理配置（可选）
    hltv_proxy_list: list[str] = []  # 代理列表


# 获取配置
plugin_config = get_plugin_config(Config)
