from dataclasses import dataclass


class RenderError(RuntimeError):
    pass


@dataclass(frozen=True)
class HelpEntry:
    command: str
    description: str = ""
    arguments: str = ""
    aliases: tuple[str, ...] = ()
    example: str = ""
    permission: str = ""


@dataclass(frozen=True)
class HelpSection:
    title: str
    entries: tuple[HelpEntry, ...] = ()
    note: str = ""


@dataclass(frozen=True)
class ParagraphBlock:
    text: str


@dataclass(frozen=True)
class HelpDocument:
    title: str
    introduction: str = ""
    sections: tuple[HelpSection, ...] = ()
    paragraphs: tuple[ParagraphBlock, ...] = ()
    tips: tuple[str, ...] = ()
    links: tuple[str, ...] = ()
    footer: str = "Generated by HakuBot"


@dataclass(frozen=True)
class RenderedPage:
    data: bytes
    width: int
    height: int
    format: str = "png"


@dataclass(frozen=True)
class RenderedDocument:
    pages: tuple[RenderedPage, ...]

