from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import List, Tuple, Optional

from .utils import get_additional_text
from ..utils.draw.cards import render_leaderboard_card, DARK_COLORS

TZ_CN = timezone(timedelta(hours=8))


def _fmt_date(d: date) -> str:
    return d.strftime("%Y.%m.%d")


async def render_today_stat_image(
    total: int, top_users: List[Tuple[str, int]], stat_date: Optional[date] = None
) -> bytes:
    """渲染“今日统计”图片（不含每日额外文案）

    Args:
        stat_date: 统计日期（默认取今天）
    """
    if stat_date is None:
        stat_date = datetime.now(TZ_CN).date()
    date_str = _fmt_date(stat_date)

    return await render_leaderboard_card(
        title="今日消息统计",
        subtitle=f"统计日期：{date_str}",
        total=total,
        total_label="总消息数",
        rows=top_users,
        footer=None,
        watermark=f"Generated by HakuBot · {date_str}",
        width=720,
        colors=DARK_COLORS,
    )


async def render_daily_stat_image(
    total: int, top_users: List[Tuple[str, int]], stat_date: date
) -> bytes:
    """渲染“每日统计”图片（包含阈值额外文案）

    注意：stat_date 是“被统计的那一天”，不等于消息发送日期。
    例如 2026.02.07 00:00 推送的统计，stat_date 应为 2026.02.06。
    """
    date_str = _fmt_date(stat_date)
    additional_text = get_additional_text(total)

    return await render_leaderboard_card(
        title="每日消息统计",
        subtitle=f"统计日期：{date_str}",
        total=total,
        total_label="总消息数",
        rows=top_users,
        footer=additional_text,
        watermark=f"Generated by HakuBot · {date_str}",
        width=720,
        colors=DARK_COLORS,
    )
