"""
HakuBot alive_stat — 统一处理 alive 命令。
显示 HakuBot + autochat 运行时间、服务器状态、进程监控、网络连通性。
"""
from datetime import datetime

from nonebot import on_command, require, get_driver
from nonebot.adapters import Bot, Event, Message
from nonebot.params import CommandArg
from nonebot.adapters.onebot.v11 import MessageSegment, GroupMessageEvent

from .runtime import save_data, get_hakubot_runtime, get_autochat_runtime, BotRuntime
from .collector import collect_server_status, ServerStatus, ProcessInfo, NetworkResult
from . import drawer

from ..utils.tools import get_logger

logger = get_logger("alive_stat")

try:
    from ..plugin_manager.enable import is_plugin_enabled  # type: ignore
except Exception:
    is_plugin_enabled = None  # type: ignore

# ================= 定时保存 & 关闭保存 =================

try:
    _driver = get_driver()
except ValueError:
    _driver = None

if _driver is not None:
    require("nonebot_plugin_apscheduler")
    from nonebot_plugin_apscheduler import scheduler

    scheduler.scheduled_job("interval", minutes=5, id="save_alive_stats")(save_data)

    @_driver.on_shutdown
    async def _():
        save_data()

# ================= 响应器 =================

alive = on_command("alive", priority=5, block=True)


@alive.handle()
async def handle_alive(bot: Bot, event: Event, args: Message = CommandArg()):
    user_id = str(event.get_user_id())
    if isinstance(event, GroupMessageEvent) and is_plugin_enabled is not None:
        if not is_plugin_enabled("alive_stat", str(event.group_id), user_id):
            await alive.finish()

    now = datetime.now()

    # 日夜模式
    arg_text = args.extract_plain_text().strip().lower()
    if "night" in arg_text:
        is_night = True
    elif "day" in arg_text:
        is_night = False
    else:
        hour = now.hour
        is_night = not (6 <= hour < 18)

    # 采集数据
    hakubot_rt = get_hakubot_runtime(now)
    autochat_rt = get_autochat_runtime(now)
    server = await collect_server_status()

    # 水印
    watermark_time = now.strftime("%H:%M:%S %b. %d %Y")
    watermark = f"Generated by HakuBot\nGenerated at {watermark_time}"

    # 绘图
    image_bytes = await drawer.draw_alive_card(
        hakubot_runtime=hakubot_rt,
        autochat_runtime=autochat_rt,
        server=server,
        watermark=watermark,
        is_night=is_night,
    )

    await alive.finish(MessageSegment.image(image_bytes))
