from nonebot import on_command
from nonebot.adapters import Bot, Event
from nonebot.params import CommandArg
from nonebot.adapters.onebot.v11 import Message, MessageSegment, GroupMessageEvent
from nonebot.exception import FinishedException

from ..plugin_manager.enable import is_plugin_enabled
from .api import fetch_event_list, fetch_event_detail
from .render import render_event_list_pic, render_event_detail_pic
from .models import EventDetail


CUSTOM_WATERMARK = "请勿转载到其他任何社交平台\nGenerated by HakuBot\nData Source: PJSK剧情站 Powered by Exmeaning\n活动中文标题及摘要由AI翻译总结，可能与资讯站/官方不同"
GLOBAL_WATERMARK_TEXT = "禁止转载至其他任何社交平台"


pjsk_list = on_command("剧情列表", priority=5, block=True)
pjsk_detail = on_command("剧情总结", priority=5, block=True)


@pjsk_list.handle()
async def handle_list(bot: Bot, event: Event):
    # 插件开关检查
    if isinstance(event, GroupMessageEvent):
        user_id = str(event.get_user_id())
        if not is_plugin_enabled("pjsk_event_summary", str(event.group_id), user_id):
            await pjsk_list.finish()

    await pjsk_list.send("正在获取剧情列表，请稍候...")

    try:
        events = await fetch_event_list(limit=20)

        # 传入水印
        pic = await render_event_list_pic(events, watermark=CUSTOM_WATERMARK, global_watermark=GLOBAL_WATERMARK_TEXT)

        await pjsk_list.finish(MessageSegment.image(pic))

    except FinishedException:
        raise
    except Exception as e:
        await pjsk_list.finish(f"获取列表失败: {str(e)}")


@pjsk_detail.handle()
async def handle_detail(bot: Bot, event: Event, args: Message = CommandArg()):
    # 插件开关检查
    if isinstance(event, GroupMessageEvent):
        user_id = str(event.get_user_id())
        if not is_plugin_enabled("pjsk_event_summary", str(event.group_id), user_id):
            await pjsk_detail.finish()

    event_id = args.extract_plain_text().strip()

    if not event_id.isdigit():
        await pjsk_detail.finish("请提供正确的数字ID，例如：剧情总结 188")

    await pjsk_detail.send(f"正在获取 Event {event_id} 的详情...")

    try:
        result = await fetch_event_detail(event_id)

        if isinstance(result, str):
            await pjsk_detail.finish(result)

        # 传入水印
        pic = await render_event_detail_pic(result, watermark=CUSTOM_WATERMARK, global_watermark=GLOBAL_WATERMARK_TEXT)

        await pjsk_detail.finish(MessageSegment.image(pic))

    except FinishedException:
        raise
    except Exception as e:
        await pjsk_detail.finish(f"处理出错: {str(e)}")
