from nonebot import on_command
from nonebot.adapters import Bot, Event
from nonebot.params import CommandArg
from nonebot.adapters.onebot.v11 import Message, MessageSegment
from nonebot.exception import FinishedException

from .api import fetch_event_list, fetch_event_detail
from .render import render_event_list_pic, render_event_detail_pic
from .models import EventDetail


CUSTOM_WATERMARK = "Generated by HakuBot\nData Source: PJSK剧情站 Powered by Exmeaning\n活动中文标题及摘要由AI翻译总结，可能与资讯站/官方不同"


pjsk_list = on_command("剧情列表", priority=5, block=True)
pjsk_detail = on_command("剧情总结", priority=5, block=True)


@pjsk_list.handle()
async def handle_list(bot: Bot, event: Event):
    await pjsk_list.send("正在获取剧情列表，请稍候...")

    try:
        events = await fetch_event_list(limit=20)

        # 传入水印
        pic = await render_event_list_pic(events, watermark=CUSTOM_WATERMARK)

        await pjsk_list.finish(MessageSegment.image(pic))

    except FinishedException:
        raise
    except Exception as e:
        await pjsk_list.finish(f"获取列表失败: {str(e)}")


@pjsk_detail.handle()
async def handle_detail(bot: Bot, event: Event, args: Message = CommandArg()):
    event_id = args.extract_plain_text().strip()

    if not event_id.isdigit():
        await pjsk_detail.finish("请提供正确的数字ID，例如：剧情总结 188")

    await pjsk_detail.send(f"正在获取 Event {event_id} 的详情...")

    try:
        result = await fetch_event_detail(event_id)

        if isinstance(result, str):
            await pjsk_detail.finish(result)

        # 传入水印
        pic = await render_event_detail_pic(result, watermark=CUSTOM_WATERMARK)

        await pjsk_detail.finish(MessageSegment.image(pic))

    except FinishedException:
        raise
    except Exception as e:
        await pjsk_detail.finish(f"处理出错: {str(e)}")