# help.py
import os
from pathlib import Path
from nonebot import get_driver
from nonebot.log import logger

# 导入共享浏览器模块
try:
    from ..utils.browser import html_to_pic

    HTMLRENDER_AVAILABLE = True
except ImportError:
    HTMLRENDER_AVAILABLE = False
    logger.warning("未检测到浏览器模块，帮助图片生成将不可用")

# ================= 配置常量 =================
# 定义保存路径：当前工作目录/data/image_processor/help.png
CACHE_DIR = Path.cwd() / "data" / "image_processor"
HELP_IMG_PATH = CACHE_DIR / "help.png"


# ================= 核心渲染逻辑 (内部使用) =================
async def _render_help_image() -> bool:
    """内部函数：执行实际的渲染和保存逻辑"""
    if not HTMLRENDER_AVAILABLE:
        return False

    # 自定义水印
    custom_watermark = "Generated by HakuBot"

    try:
        # CSS 样式
        css = """
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap');

        body {
            font-family: 'Noto Sans SC', sans-serif;
            background-color: #f0f2f5;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .container {
            width: 800px;
            background: linear-gradient(135deg, #ffffff 0%, #f8f9fa 100%);
            border-radius: 20px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            overflow: hidden;
            padding-bottom: 20px;
        }

        .header {
            background: linear-gradient(135deg, #6c5ce7 0%, #a29bfe 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }

        .header h1 {
            margin: 0;
            font-size: 36px;
            font-weight: 700;
            letter-spacing: 2px;
        }

        .header p {
            margin: 10px 0 0;
            opacity: 0.9;
            font-size: 16px;
            font-weight: 400;
        }

        .content {
            padding: 30px 40px 10px 40px;
            display: grid;
            grid-template-columns: 1fr;
            gap: 25px;
        }

        .section {
            background: white;
            border-radius: 12px;
            border: 1px solid #edf2f7;
            box-shadow: 0 4px 6px rgba(0,0,0,0.02);
            overflow: hidden;
        }

        .section-title {
            background: #f8f9fa;
            padding: 12px 20px;
            font-size: 18px;
            font-weight: 700;
            color: #2d3436;
            border-bottom: 1px solid #edf2f7;
            display: flex;
            align-items: center;
        }

        .section-title::before {
            content: '';
            display: inline-block;
            width: 4px;
            height: 18px;
            background: #6c5ce7;
            margin-right: 10px;
            border-radius: 2px;
        }

        .cmd-list {
            padding: 15px 20px;
        }

        .cmd-item {
            display: flex;
            align-items: baseline;
            margin-bottom: 12px;
            line-height: 1.6;
        }

        .cmd-item:last-child {
            margin-bottom: 0;
        }

        .cmd {
            font-family: 'Consolas', monospace;
            background: #eef2ff;
            color: #4834d4;
            padding: 4px 8px;
            border-radius: 6px;
            font-weight: 700;
            font-size: 16px;
            margin-right: 15px;
            white-space: nowrap;
            min-width: 140px;
            text-align: right;
            border: 1px solid #e0e7ff;
        }

        .desc {
            color: #636e72;
            font-size: 15px;
            flex: 1;
        }

        .footer {
            margin-top: 10px;
            padding: 20px 40px;
            background: #f1f8ff;
            border-radius: 12px;
            margin-left: 40px;
            margin-right: 40px;
            border: 1px dashed #74b9ff;
        }

        .tip-title {
            color: #0984e3;
            font-weight: 700;
            margin-bottom: 10px;
            display: block;
        }

        .tip-item {
            color: #576574;
            font-size: 14px;
            margin-bottom: 6px;
            position: relative;
            padding-left: 15px;
        }

        .tip-item::before {
            content: '•';
            position: absolute;
            left: 0;
            color: #0984e3;
        }

        .watermark {
            text-align: right;
            margin-top: 15px;
            margin-right: 45px;
            margin-bottom: 5px;
            color: #b2bec3;
            font-size: 12px;
            font-weight: 500;
            letter-spacing: 1px;
            font-family: 'Consolas', sans-serif;
        }
        """

        # HTML 结构
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>{css}</style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>图像处理工具箱</h1>
                    <p>Image Processor Plugin</p>
                </div>

                <div class="content">

                    <div class="section">
                        <div class="section-title">GIF & 动态处理</div>
                        <div class="cmd-list">
                            <div class="cmd-item">
                                <span class="cmd">img倒放</span>
                                <span class="desc">将 GIF 倒序播放，生成倒放效果</span>
                            </div>
                            <div class="cmd-item">
                                <span class="cmd">imgx [倍数]</span>
                                <span class="desc">调整 GIF 播放速度 (0.1 - 5.0倍)</span>
                            </div>
                            <div class="cmd-item">
                                <span class="cmd">img旋转 [倍速]</span>
                                <span class="desc">让图片自转生成 GIF 动画 (默认顺时针)</span>
                            </div>
                            <div class="cmd-item">
                                <span class="cmd">img顺/逆时针</span>
                                <span class="desc">指定方向旋转，支持静态图和 GIF</span>
                            </div>
                        </div>
                    </div>

                    <div class="section">
                        <div class="section-title">图片编辑</div>
                        <div class="cmd-list">
                            <div class="cmd-item">
                                <span class="cmd">imgcut</span>
                                <span class="desc">智能去除背景 (抠图)</span>
                            </div>
                            <div class="cmd-item">
                                <span class="cmd">img镜像</span>
                                <span class="desc">图片水平翻转 (左右镜像)</span>
                            </div>
                            <div class="cmd-item">
                                <span class="cmd">img上镜像</span>
                                <span class="desc">图片垂直翻转 (上下镜像)</span>
                            </div>
                            <div class="cmd-item">
                                <span class="cmd">img对称</span>
                                <span class="desc">取左半部分进行镜像对称</span>
                            </div>
                            <div class="cmd-item">
                                <span class="cmd">img[方向]对称</span>
                                <span class="desc">支持 左 / 右 / 上 / 下 / 中心 对称</span>
                            </div>
                        </div>
                    </div>

                    <div class="section">
                        <div class="section-title">视频工具</div>
                        <div class="cmd-list">
                            <div class="cmd-item">
                                <span class="cmd">imggif</span>
                                <span class="desc">将视频转换为 GIF (支持最长 60 秒)</span>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="footer">
                    <span class="tip-title">💡 使用小贴士</span>
                    <div class="tip-item">所有命令均需 [回复] 包含图片或视频的消息来触发</div>
                    <div class="tip-item">处理大尺寸 GIF 或长视频可能需要几十秒，请耐心等待</div>
                </div>

                <div class="watermark">{custom_watermark}</div>
            </div>
        </body>
        </html>
        """

        # 确保目录存在
        CACHE_DIR.mkdir(parents=True, exist_ok=True)

        # 渲染图片
        img_bytes = await html_to_pic(
            html=html,
            viewport={"width": 840, "height": 10}
        )

        # 保存到持久化目录
        with open(HELP_IMG_PATH, "wb") as f:
            f.write(img_bytes)

        logger.info(f"帮助图片已生成并缓存至: {HELP_IMG_PATH}")
        return True

    except Exception as e:
        logger.error(f"HTMLRender 生成帮助图片失败: {e}")
        return False


# ================= Startup Hook =================
@get_driver().on_startup
async def init_help_image():
    """Bot启动时自动生成帮助图片"""
    logger.info("正在初始化图片处理插件帮助菜单...")
    success = await _render_help_image()
    if not success:
        logger.warning("帮助图片初始化失败，将在首次调用时重试")


# ================= 对外接口 =================
async def generate_help_image() -> str:
    """获取帮助图片路径（优先使用缓存）"""
    # 1. 如果文件存在，直接返回路径
    if HELP_IMG_PATH.exists():
        return str(HELP_IMG_PATH)

    # 2. 如果文件不存在（启动时生成失败或被删除），尝试重新生成
    logger.info("帮助图片缓存不存在，正在重新生成...")
    success = await _render_help_image()

    if success:
        return str(HELP_IMG_PATH)
    else:
        return ""


async def get_help_text() -> str:
    """获取纯文本帮助信息（备用）"""
    return """
【图像处理插件帮助】

[GIF/动画]
• img倒放 : GIF倒放
• imgx [倍数] : GIF倍速 (0.1-5.0)
• img旋转 [倍速] : 自转GIF (默认顺时针)
• img逆时针 [倍速] : 逆时针自转

[图片编辑]
• imgcut : AI智能抠图
• img镜像 / img上镜像 : 水平/垂直翻转
• img对称 / img左对称 : 左半镜像
• img右/上/下/中心对称 : 其它方向对称

[视频]
• imggif : 视频转GIF (限60s)

提示：请回复包含图片或视频的消息使用。
"""
