from nonebot import on_command
from nonebot.adapters.onebot.v11 import Bot, Event, GroupMessageEvent, MessageSegment, Message, MessageEvent
from nonebot.exception import FinishedException
from nonebot.log import logger
from nonebot.params import CommandArg
from nonebot.permission import SUPERUSER

# 导入渲染函数
from .render import render_sign_image_v2
from .message import message_sign

import random
import json
from datetime import date
from pathlib import Path
from typing import Dict, Any, Optional

# 导入管理模块
from ..plugin_manager.enable import is_plugin_enabled
from ..utils.common import create_exact_command_rule

# --- 配置 ---
DATA_FILE = Path("data/draw_lots/records.json")
# 缓存目录
CACHE_DIR = Path("data/draw_lots/cache")

# 确保目录存在
DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
CACHE_DIR.mkdir(parents=True, exist_ok=True)

# 水印设置
WATERMARK_TEXT = "Generated by HakuBot"


# --- 数据操作函数 ---

def load_records() -> Dict[str, Dict[str, Any]]:
    """加载抽签记录"""
    if DATA_FILE.exists():
        with open(DATA_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}


def save_records(records: Dict[str, Dict[str, Any]]):
    """保存抽签记录"""
    with open(DATA_FILE, 'w', encoding='utf-8') as f:
        json.dump(records, f, ensure_ascii=False, indent=2)


def get_user_record(user_id: str) -> Optional[int]:
    """
    获取用户今天的抽签记录 ID
    返回: int (index) 或 None (未抽)
    -1 代表空签
    """
    records = load_records()
    today = str(date.today())

    user_data = records.get(user_id)
    if user_data and user_data.get("date") == today:
        return user_data.get("sign_index")
    return None


def save_user_record(user_id: str, sign_index: int):
    """保存用户今天的抽签记录 ID"""
    records = load_records()
    today = str(date.today())
    records[user_id] = {
        "date": today,
        "sign_index": sign_index
    }
    save_records(records)


async def get_or_render_image(sign_index: int, force_refresh: bool = False) -> bytes:
    """
    获取图片：优先从缓存读取，没有则渲染并保存
    :param sign_index: 签文索引，-1 表示空签
    :param force_refresh: 是否强制重新渲染（覆盖缓存）
    """
    # 1. 确定缓存文件名
    if sign_index == -1:
        cache_file = CACHE_DIR / "empty.png"
        sign_content = "空签"
    else:
        # 确保 index 在范围内
        if 0 <= sign_index < len(message_sign):
            cache_file = CACHE_DIR / f"{sign_index}.png"
            sign_content = message_sign[sign_index]
        else:
            # 异常情况，回落到空签
            cache_file = CACHE_DIR / "error.png"
            sign_content = "空签"

    # 2. 检查缓存是否存在 (如果不是强制刷新)
    if not force_refresh and cache_file.exists():
        logger.debug(f"Draw lots: Cache hit for index {sign_index}")
        return cache_file.read_bytes()

    # 3. 渲染新图片
    logger.info(f"Draw lots: Rendering image for index {sign_index} (Force: {force_refresh})")
    img_bytes = await render_sign_image_v2(sign_content, sign_index, WATERMARK_TEXT)

    # 4. 写入缓存
    try:
        with open(cache_file, "wb") as f:
            f.write(img_bytes)
    except Exception as e:
        logger.error(f"Draw lots: Failed to save cache: {e}")

    return img_bytes


# --- 响应处理器 ---

command = on_command('抽签', priority=6, rule=create_exact_command_rule("抽签"))


@command.handle()
async def lq_(bot: Bot, event: MessageEvent):
    user_id = str(event.user_id)

    # 群聊权限检查
    if isinstance(event, GroupMessageEvent):
        if not is_plugin_enabled("draw_lots", str(event.group_id), user_id):
            await command.finish("抽签功能当前已被禁用")

    sign_index = -1
    is_retry = False

    # 检查今天是否已经抽过
    record_index = get_user_record(user_id)

    if record_index is not None:
        sign_index = record_index
        is_retry = True
    else:
        # 抽签逻辑
        a = random.randint(0, 100)
        if a >= 5:  # 95% 概率抽中正签
            # 随机选取一个 index
            sign_index = random.randint(0, len(message_sign) - 1)
        else:
            sign_index = -1  # 空签代码

        save_user_record(user_id, sign_index)

    # 构建消息
    msg = Message()
    # 添加回复引用
    msg.append(MessageSegment.reply(event.message_id))

    # 提示语
    if is_retry:
        msg.append("你今天已经抽过签啦，这是你今天的签文：\n")

    # 获取/生成图片并发送
    try:
        img_bytes = await get_or_render_image(sign_index)
        msg.append(MessageSegment.image(img_bytes))
        await command.finish(msg, at_sender=True)
    except FinishedException:
        raise
    except Exception as e:
        logger.error(f"抽签处理失败: {e}")
        # 降级文本
        content = "空签" if sign_index == -1 else message_sign[sign_index]
        await command.finish(f"图片生成失败，签文内容：\n{content}", at_sender=True)


# --- 缓存管理命令 ---

gen_cache_cmd = on_command("刷新签文缓存", permission=SUPERUSER, priority=1, block=True)


@gen_cache_cmd.handle()
async def _(bot: Bot, event: Event, args: Message = CommandArg()):
    arg_text = args.extract_plain_text().strip()

    # 情况1：指定了序号 (例如 "刷新签文缓存 1")
    if arg_text:
        try:
            n = int(arg_text)

            # 定义 0 为空签，1-N 为对应签文
            if n == 0:
                target_idx = -1
                label = "空签"
            else:
                target_idx = n - 1
                label = f"第{n}番"

            # 范围检查
            if target_idx != -1 and not (0 <= target_idx < len(message_sign)):
                await gen_cache_cmd.finish(f"❌ 序号错误：请输入 0 (空签) 或 1-{len(message_sign)} 之间的数字。")

            await gen_cache_cmd.send(f"🎨 正在强制重新渲染 {label}...")

            # 强制刷新
            await get_or_render_image(target_idx, force_refresh=True)

            await gen_cache_cmd.finish(f"✅ {label} 渲染完成并已更新缓存！")

        except ValueError:
            await gen_cache_cmd.finish("❌ 参数错误，请输入数字序号。")

    # 情况2：未指定序号 (生成全部)
    else:
        await gen_cache_cmd.send("🚀 开始检查并补充签文缓存...")

        success_count = 0
        total = len(message_sign)

        try:
            # 1. 检查空签 (force_refresh=False, 仅当不存在时生成)
            await get_or_render_image(-1, force_refresh=False)

            # 2. 检查所有正签
            for i in range(total):
                if (i + 1) % 10 == 0:
                    logger.info(f"[Draw Lots] 进度: {i + 1}/{total}")

                # force_refresh=False: 仅生成缺失的，跳过已存在的
                await get_or_render_image(i, force_refresh=False)
                success_count += 1

            await gen_cache_cmd.finish(
                f"✅ 缓存检查完毕！\n缓存目录: {CACHE_DIR.absolute()}\n(注意：批量模式仅生成缺失图片，如需更新样式请使用'刷新签文缓存 <序号>'指定重绘)")

        except Exception as e:
            logger.error(f"生成缓存时发生错误: {e}")
            await gen_cache_cmd.finish(f"❌ 生成过程中出错: {e}")
