from io import BytesIO
from datetime import datetime
from nonebot.log import logger
from .config import FONT_FILE

# === 图像处理库 ===
try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    logger.error("请安装 Pillow: pip install Pillow")
    Image = None

def add_watermark(img_bytes: bytes, config: dict) -> bytes:
    """
    图片后期处理：添加水印和背景扩展
    """
    if not Image:
        return img_bytes

    image = Image.open(BytesIO(img_bytes))

    # 如果是 RGBA 模式 (PNG)，转为 RGB 以便保存为 JPEG
    if image.mode == 'RGBA':
        image = image.convert('RGB')

    width, height = image.size

    # 自动吸取背景色
    try:
        bg_color = image.getpixel((0, height - 1))
    except Exception:
        bg_color = (255, 255, 255)

    # 设置扩展区域高度
    padding_bottom = 160
    new_height = height + padding_bottom

    # 创建新画布
    new_image = Image.new("RGB", (width, new_height), bg_color)
    new_image.paste(image, (0, 0))

    draw = ImageDraw.Draw(new_image)

    # 加载字体
    try:
        if FONT_FILE.exists():
            font = ImageFont.truetype(str(FONT_FILE), 24)
        else:
            font = ImageFont.truetype("arial.ttf", 24)
    except Exception:
        logger.warning("字体加载失败，使用默认位图字体")
        font = ImageFont.load_default()

    current_time_str = datetime.now().strftime("%H:%M:%S %b. %d %Y")

    text_lines = [
        config.get("watermark_text_1", "Designed and Powered by SnowyBot"),
        config.get("watermark_text_2", "Generated by HakuBot"),
        current_time_str
    ]

    # 绘制文字 (右对齐)
    current_y = height + 20
    margin_right = 40
    line_spacing = 15
    text_color = (160, 160, 160)

    for line in text_lines:
        if hasattr(draw, "textbbox"):
            bbox = draw.textbbox((0, 0), line, font=font)
            text_w = bbox[2] - bbox[0]
            text_h = bbox[3] - bbox[1]
        else:
            text_w, text_h = draw.textsize(line, font=font)

        x = width - text_w - margin_right
        draw.text((x, current_y), line, font=font, fill=text_color)
        current_y += text_h + line_spacing

    # 导出为 JPEG
    output = BytesIO()
    new_image.save(output, format="JPEG", quality=85)
    return output.getvalue()
